<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ZHumphrey-SP6i7-intern" failures="3" tests="5" name="test.TweetCollectionTest" time="0.033" errors="0" timestamp="2021-09-26T19:12:30 CDT" skipped="0">
  <testcase classname="test.TweetCollectionTest" name="testGetTweetsByUser" time="0.005">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng@7.4.0/org.testng.Assert.fail(Assert.java:99)
at org.testng@7.4.0/org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng@7.4.0/org.testng.Assert.assertTrue(Assert.java:45)
at org.testng@7.4.0/org.testng.Assert.assertTrue(Assert.java:55)
at project1/test.TweetCollectionTest.testGetTweetsByUser(TweetCollectionTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng@7.4.0/org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng@7.4.0/org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng@7.4.0/org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng@7.4.0/org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng@7.4.0/org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng@7.4.0/org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng@7.4.0/org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng@7.4.0/org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng@7.4.0/org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng@7.4.0/org.testng.TestRunner.run(TestRunner.java:596)
at org.testng@7.4.0/org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng@7.4.0/org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng@7.4.0/org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng@7.4.0/org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng@7.4.0/org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng@7.4.0/org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng@7.4.0/org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng@7.4.0/org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng@7.4.0/org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng@7.4.0/org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testGetTweetsByUser -->
  <system-out/>
  <testcase classname="test.TweetCollectionTest" name="testGetAllTweetIds" time="0.004"/>
  <system-out/>
  <testcase classname="test.TweetCollectionTest" name="testRemoveTweet" time="0.003">
    <failure message="expected [1] but found [0]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at org.testng@7.4.0/org.testng.Assert.fail(Assert.java:99)
at org.testng@7.4.0/org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng@7.4.0/org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng@7.4.0/org.testng.Assert.assertEquals(Assert.java:122)
at org.testng@7.4.0/org.testng.Assert.assertEquals(Assert.java:907)
at org.testng@7.4.0/org.testng.Assert.assertEquals(Assert.java:917)
at project1/test.TweetCollectionTest.testRemoveTweet(TweetCollectionTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng@7.4.0/org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng@7.4.0/org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng@7.4.0/org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng@7.4.0/org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng@7.4.0/org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng@7.4.0/org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng@7.4.0/org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng@7.4.0/org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng@7.4.0/org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng@7.4.0/org.testng.TestRunner.run(TestRunner.java:596)
at org.testng@7.4.0/org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng@7.4.0/org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng@7.4.0/org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng@7.4.0/org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng@7.4.0/org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng@7.4.0/org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng@7.4.0/org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng@7.4.0/org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng@7.4.0/org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng@7.4.0/org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testRemoveTweet -->
  <system-out/>
  <testcase classname="test.TweetCollectionTest" name="testGetTweetById" time="0.003"/>
  <system-out/>
  <testcase classname="test.TweetCollectionTest" name="testAddTweet" time="0.018">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng@7.4.0/org.testng.Assert.fail(Assert.java:99)
at org.testng@7.4.0/org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng@7.4.0/org.testng.Assert.assertTrue(Assert.java:45)
at org.testng@7.4.0/org.testng.Assert.assertTrue(Assert.java:55)
at project1/test.TweetCollectionTest.testAddTweet(TweetCollectionTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng@7.4.0/org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng@7.4.0/org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng@7.4.0/org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng@7.4.0/org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng@7.4.0/org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng@7.4.0/org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng@7.4.0/org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng@7.4.0/org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng@7.4.0/org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng@7.4.0/org.testng.TestRunner.run(TestRunner.java:596)
at org.testng@7.4.0/org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng@7.4.0/org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng@7.4.0/org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng@7.4.0/org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng@7.4.0/org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng@7.4.0/org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng@7.4.0/org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng@7.4.0/org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng@7.4.0/org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng@7.4.0/org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testAddTweet -->
  <system-out/>
</testsuite> <!-- test.TweetCollectionTest -->
